name: run python style checks

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositor
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dev dependencies
        run: pip install flake8 pydocstyle

      - name: Run pydocstyle 
        run: |
          pydocstyle hsi_wizard
          
      - name: Run flake8
        run: |
          flake8 hsi_wizard
